### ISSUE TITLE
gl.Init fails in gl21 with Intel GPU on Windows

### ISSUE THREAD

**Issue by ghost** [chsc/gogl#14]
Hey,
I have a laptop with a HD3000 Intel GPU and a discrete AMD GPU both with recent drivers. AMD supports OpenGL 4.1 and Intel 3.1.
OS: Windows 7 64bit

Source: http://pastebin.com/sKxUner5

This simple example fails for me with the Intel GPU with the following error:

unable to initialize VERSION_1_2_DEPRECATEDpanic: runtime error: call of nil func value
[signal 0xc0000005 code=0x8 addr=0x0 pc=0x0]

goroutine 1 [syscall]:
github.com/chsc/gogl/gl21._Cfunc_goglCreateShader(0x8b31, 0x25800000320)
    C:/Users/Manuel/AppData/Local/Temp/go-build118120071/github.com/chsc/gogl/gl21/_obj/_cgo_defun.c:786 +0x32
github.com/chsc/gogl/gl21.CreateShader(0x8b31, 0xf84004d620, 0x2b, 0x0)
    C:/Users/Manuel/AppData/Local/Temp/go-build118120071/github.com/chsc/gogl/gl21/_obj/gl21.cgo1.go:4890 +0x26
main.main()
    C:/Users/Manuel/Dev/go opengl test/bugrep.go:47 +0x344

I checked that all needed functions are exposed by the Intel driver with glew and everything is there.
Changing the gl version to gl33 results in the mesesage "unable to initialize VERSION_3_2" which is correct since 3.2 is not supported by the driver but the example works then.

With the AMD gpu the example works correct with gl21 and gl33.

I found the following page, maybe it helps you: http://www.opengl.org/wiki/Load_OpenGL_Functions
I would like to help you testing but I am new to Go and OpenGL and probably can not help you with code.
Thanks for the nice bindings

**Comment by chsc** [comment]
I've tested your sample program with an AMD radeon and an nvidia graphics card (ubuntu 64+32 bit). It works without any problems. I don't know why it doesn't find the entry points on Intel hardware.

gl33 is a pure OpenGL 3.3 core profile package, so the VERSION_ \* _ \* _DEPRECATED error doesn't show up.
If you want a GL 3.1 core package: simply follow the instructions in the README.md file. I think this should work for Intel's HD3000.
